extends: default

rules:
    document-start: disable
    line-length:
        max: 120
    truthy:
        allowed-values: ["true", "false", "yes", "no", "on", "off"]
    comments:
        min-spaces-from-content: 1
    indentation:
        spaces: 4
        indent-sequences: consistent
