extends: default

rules:
  line-length:
    max: 120
  truthy:
    allowed-values: ["true", "false", "yes", "no"]
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 4
    indent-sequences: consistent
